In [1]:
import numpy as np

In [2]:
myArr = np.arange (0,15)

In [3]:
myArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
myArr[5]

5

## slicing

In [6]:
myArr[3:8]    

array([3, 4, 5, 6, 7])

In [7]:
myArr[3:8] = -5

In [8]:
myArr

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
arr2 = np.arange(0,24)

In [10]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
slicing_arr = arr2[4:9] 

In [12]:
slicing_arr

array([4, 5, 6, 7, 8])

In [13]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
type(slicing_arr) 

numpy.ndarray

In [15]:
slicing_arr[:] = 700

In [16]:
slicing_arr

array([700, 700, 700, 700, 700])

In [17]:
arr2

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [18]:
arr3 = np.arange(0,24)

In [19]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
arr3Copy = arr3.copy()

In [21]:
arr3Copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
arr3CopySlicing = arr3Copy[3:6]

In [24]:
arr3CopySlicing [:] = 800

In [25]:
arr3CopySlicing

array([800, 800, 800])

In [26]:
arr3Copy

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [27]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [28]:
my_list = [[10,20,30,],[20,30,40],[40,50,60]]

In [29]:
my_matrix = np.array(my_list)

In [30]:
my_matrix

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [31]:
my_matrix[0]

array([10, 20, 30])

In [32]:
my_matrix[1][2]

40

In [33]:
my_matrix[1,2]

40

In [34]:
my_matrix[1:, 2]

array([40, 60])

In [35]:
my_matrix[2:, 2]

array([60])

In [36]:
my_matrix[0:, 2]

array([30, 40, 60])

In [37]:
my_matrix[2:, 2:]

array([[60]])

In [38]:
my_matrix[1:, 1:]

array([[30, 40],
       [50, 60]])

In [39]:
new_list = [[0,1,2,3,4,],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [42]:
new_matrix = np.array(new_list)

In [43]:
new_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
new_matrix[2]

array([10, 11, 12, 13, 14])

In [45]:
new_matrix[[0,2,4]]   # index listesi (fancy indeks)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [46]:
new_matrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## numpy operasyonlar

In [49]:
arr4 = np.random.randint(1,100,20)

In [50]:
arr4

array([91, 64,  5, 72, 92, 80, 77, 43, 93, 36,  3, 37, 55, 32, 50,  4, 96,
       27, 27, 31])

In [51]:
arr4 > 24

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [52]:
arr4

array([91, 64,  5, 72, 92, 80, 77, 43, 93, 36,  3, 37, 55, 32, 50,  4, 96,
       27, 27, 31])

In [53]:
arr5 = arr4 > 24

In [54]:
arr5

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [56]:
arr4[arr5]

array([91, 64, 72, 92, 80, 77, 43, 93, 36, 37, 55, 32, 50, 96, 27, 27, 31])

In [57]:
arr4

array([91, 64,  5, 72, 92, 80, 77, 43, 93, 36,  3, 37, 55, 32, 50,  4, 96,
       27, 27, 31])

In [58]:
arr4[arr4>24]

array([91, 64, 72, 92, 80, 77, 43, 93, 36, 37, 55, 32, 50, 96, 27, 27, 31])

In [60]:
arr6 = np.arange(0,24)

In [61]:
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [62]:
arr6 + arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [63]:
arr6 * arr6

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [64]:
arr6 - arr6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [65]:
arr6 / arr6   # 0 / 0 nan

C:\Users\Ali iskurt\AppData\Local\Temp\ipykernel_16060\1649343207.py:1: RuntimeWarning: invalid value encountered in divide
  arr6 / arr6


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [66]:
np.sqrt(arr6)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [67]:
np.max(arr6)

23

In [68]:
np.min(arr6)

0